Feature: Operator update booking with setting passenger/luggage number
    As an operator,
    I want to update booking

    Background:

    Scenario: 01. Check case update booking with setting passenger/luggage number
        When I send a web socket from CC request with event and data
            | event         | requestData                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
            | editBookingCC | {"bookId":"3123519510","dispatch3rd":false,"retryDispatch":false,"dispatchType":0,"drvInfo":{"phone":""},"psgInfo":{"creditInfo":{}},"mDispatcherInfo":{},"request":{"pickUpTime":"Now","note":"","vehicleType":["Da Nang, Vietnam"],"vehicleTypeRequest":"Da Nang, Vietnam","pickup":{"geo":[108.20806,16.0612533],"cityName":"Đà Nẵng","address":"Tổ 6, Khu Phố Hà Trung, Phường Thạc Gián, Quận Thanh Khê, Thạc Gián, Thanh Khê, Đà Nẵng 550000","zipCode":"550000","country":"VN","from":"gg","instructionLink":""},"destination":{"geo":[108.210548,16.064333],"cityName":"Đà Nẵng","address":"26 Hàm Nghi, Thạc Gián, Q. Thanh Khê, Đà Nẵng 550000","zipCode":"550000","country":"VN","from":"gg","instructionLink":""},"moreInfo":{"flightInfo":{"type":-1,"airline":"","flightNumber":""}},"estimate":{"distance":"0.4mi","time":"2 mins","estimateValue":176,"fare":{"basicFare":16.75,"etaFare":17.4,"airportFee":0,"meetDriverFee":0,"rushHourFee":0,"techFee":0,"bookingFee":0,"tollFee":0,"tax":0.65,"tip":0,"minFare":1,"normalFare":true,"route":"","routeId":"","reverseRoute":false,"min":false,"otherFees":5,"promoAmount":5,"serviceFee":0,"typeRate":0,"totalWithoutPromo":22.4,"dynamicSurcharge":0,"surchargeParameter":0,"dynamicFare":0,"shortTrip":false}},"type":0,"typeRate":0,"paymentType":1,"packageRateId":"","duration":0,"packageRateName":"","tip":0,"promo":"PAY01","promoValue":"-5C$","rideSharing":false,"paxNumber":-1,"luggageNumber":-1,"extraDestination":[],"services":[{"fee":5,"active":false,"name":"Nghia","type":"Optional","serviceId":"5daeda1c95982474f7cfa655"}]},"operator":{"name":"nghia huynh"}} |
        Then I should get the object result matches with
            | response                                                                                                                                         |
            | {"code":200,"reservation":false,"paramUpdate":{"request.paxNumber":2,"request.luggageNumber":3,"dispatchType":0,"request.travelMode":"driving"}} |
