Feature: Create order delivery
    As an passenger,
    I want to create order

    Background:
        Given an api token after logined command center
    # Scenario: 01. Check case create delivery cashOnDelivery booking success
    #     Given I want to register account
    #         | platform | fleetId | phone         | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | haidr   | +447400123789 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs delivery with data
    #         | request.paymentType |
    #         | 16                  |
    #     Then I should get the object result matches with
    #         | response      |
    #         | {"code":true} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"haidr","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                                    |
    #         | {"res":{"list":[{"jobType":"delivery","delivery":true,"superHelper":false,"intercity":false,"deliveryInfo":{"cashOnDelivery":true,"cashOnPickUp":false}}]}} |

    # Scenario: 02. Check case save info pickup delivery
    #     Given I want to register account
    #         | platform | fleetId | phone         | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | haidr   | +447400123789 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs delivery with data
    #         | deliveryInfo.pickup                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"name":"Nghia Huynh","phone":"+7400123789","address":{"locationDetails":"Duy Tan University","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Duy Tan University","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
    #         | {"code":true, "pickup":{"locationDetails":"Duy Tan University","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Duy Tan University","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"}} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"haidr","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    #         | {"res":{"list":[{"jobType":"delivery","delivery":true,"superHelper":false,"intercity":false,"request":{"pickup":{"geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Duy Tan University","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","cityName":"Da Nang","country":"VN"}}}]}} |

    # Scenario: 03. Check case save info car type request
    #     Given I want to register account
    #         | platform | fleetId | phone         | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | haidr   | +447400123789 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs delivery with data
    #         | deliveryInfo.pickup                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"name":"Nghia Huynh","phone":"+7400123789","address":{"locationDetails":"Duy Tan University","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Duy Tan University","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"}} |
    #     Then I should get the object result matches with
    #         | response      |
    #         | {"code":true} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"haidr","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                                                                                   |
    #         | {"res":{"list":[{"jobType":"delivery","delivery":true,"superHelper":false,"intercity":false,"request":{"vehicleType":["Da Nang, Vietnam","Haidr","Luxury","Delivery"],"vehicleTypeRequest":"Delivery"}}]}} |

    # Scenario: 04. Check case save info recipients of delivery booking
    #     Given I want to register account
    #         | platform | fleetId | phone         | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | haidr   | +447400123789 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs delivery with data
    #         | deliveryInfo.recipients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
    #         | [{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Bao tang Cham","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":1,"menuData":{"menuId":"1","selectedItems":["1"]}}] |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
    #         | {"code":true,"info":{"deliveryInfo":{"recipients":[{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Bao tang Cham","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"}}]}}} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"haidr","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    #         | {"res":{"list":[{"jobType":"delivery","delivery":true,"superHelper":false,"intercity":false,"deliveryInfo":{"recipients":[{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Bao tang Cham","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"}}]}}]}} |

    # Scenario: 05. Check case save info merchants of delivery booking
    #     Given I want to register account
    #         | platform | fleetId | phone         | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | haidr   | +447400123789 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs delivery with data
    #         | deliveryInfo.merchants                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | [{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Bao tang Cham","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":1,"menuData":{"menuId":"1","selectedItems":["1"]}}] |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    #         | {"code":true,"info":{"deliveryInfo":{"merchants":[{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Bao tang Cham","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"}}]}}} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"haidr","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    #         | {"res":{"list":[{"jobType":"delivery","delivery":true,"superHelper":false,"intercity":false,"deliveryInfo":{"merchants":[{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Bao tang Cham","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2228928,16.0748032],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"}}]}}]}} |

    # Scenario: 06. Check case create delivery cashOnPickUp booking success
    #     Given I want to register account
    #         | platform | fleetId | phone         | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | haidr   | +447400123789 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs delivery with data
    #         | deliveryInfo.cashOnDelivery | deliveryInfo.cashOnPickUp |
    #         | false                       | true                      |
    #     Then I should get the object result matches with
    #         | response      |
    #         | {"code":true} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"haidr","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                                    |
    #         | {"res":{"list":[{"jobType":"delivery","delivery":true,"superHelper":false,"intercity":false,"deliveryInfo":{"cashOnDelivery":false,"cashOnPickUp":true}}]}} |

    Scenario: 07. Check case save info estimate from pick up to recipient is 2 point of delivery booking
        Given I want to register account
            | platform | fleetId  | phone        | appType   | verifyCode | ime             | appName | rv      | password |
            | android  | delivery | +84348811100 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

        # cashBySender: 16, cashByRecipient: 17
        When Passenger create order jobs delivery with data
            | request.fleetId | request.vehicleTypeRequest | deliveryInfo.merchants | deliveryInfo.recipients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | delivery        | DeliveryFeePer             | []                     | [{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"158 Le Duan","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2145971, 16.0704755],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":2,"menuData":{"menuId":"1","selectedItems":["1"]}},{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Bao tang Cham","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.220313, 16.0682048],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":1,"menuData":{"menuId":"1","selectedItems":["1"]}}] |
        Then I should get the object result matches with
            | response                                                                                                                                                                                |
            | {"code":true,"info":{"estimate":{"fare":{"etaFare":86440,"recipients":[{"deliveryFee":26083.33,"techFee":4000,"total":35300},{"deliveryFee":39283.33,"techFee":4000,"total":51140}]}}}} |

    # Scenario: 08. Check case save info estimate from pick up to recipient is 1 point of delivery booking
    #     Given I want to register account
    #         | platform | fleetId  | phone        | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | delivery | +84348811100 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     When Passenger create order jobs delivery with data
    #         | request.fleetId | request.vehicleTypeRequest | deliveryInfo.merchants | deliveryInfo.recipients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
    #         | delivery        | DeliveryFeePer             | []                     | [{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"158 Le Duan","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2145971, 16.0704755],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":2,"menuData":{"menuId":"1","selectedItems":["1"]}}] |
    #     Then I should get the object result matches with
    #         | response                                                                                                                                        |
    #         | {"code":true,"info":{"estimate":{"fare":{"etaFare":35300,"recipients":[{"deliveryFee":26083.33,"tax":5216.67,"techFee":4000,"total":35300}]}}}} |

    # Scenario: 09. Check case save info payment type cashBySender
    #     Given I want to register account
    #         | platform | fleetId  | phone        | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | delivery | +84348811100 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs delivery with data
    #         | request.paymentType | request.fleetId | request.vehicleTypeRequest | deliveryInfo.merchants | deliveryInfo.recipients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
    #         | 16                  | delivery        | DeliveryFeePer             | []                     | [{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"158 Le Duan","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2145971, 16.0704755],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":2,"menuData":{"menuId":"1","selectedItems":["1"]}},{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Bao tang Cham","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.220313, 16.0682048],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":1,"menuData":{"menuId":"1","selectedItems":["1"]}}] |
    #     Then I should get the object result matches with
    #         | response      |
    #         | {"code":true} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"delivery","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                     |
    #         | {"res":{"list":[{"jobType":"delivery","delivery":true,"superHelper":false,"intercity":false,"request":{"paymentType":16}}]}} |

    # Scenario: 10. Check case save info payment type cashBySender
    #     Given I want to register account
    #         | platform | fleetId  | phone        | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | delivery | +84348811100 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |
    #     When Passenger create order jobs delivery with data
    #         | request.paymentType | request.fleetId | request.vehicleTypeRequest | deliveryInfo.merchants | deliveryInfo.recipients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
    #         | 17                  | delivery        | DeliveryFeePer             | []                     | [{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"158 Le Duan","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2145971, 16.0704755],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":2,"menuData":{"menuId":"1","selectedItems":["1"]}},{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Bao tang Cham","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.220313, 16.0682048],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":1,"menuData":{"menuId":"1","selectedItems":["1"]}}] |
    #     Then I should get the object result matches with
    #         | response      |
    #         | {"code":true} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"delivery","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                     |
    #         | {"res":{"list":[{"jobType":"delivery","delivery":true,"superHelper":false,"intercity":false,"request":{"paymentType":17}}]}} |

    # Scenario: 11. Check case save info shop for you
    #     Given I want to register account
    #         | platform | fleetId | phone         | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | haidr   | +447400123789 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs shop for you "ASAP" with data
    #         | jupiter.jobType | request.paymentType | request.fleetId | request.vehicleTypeRequest | deliveryInfo.merchants                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | deliveryInfo.recipients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    #         | shopForYou      | 16                  | haidr           | Delivery                   | [{"name":"Nghia Huynh","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Hoang dieu, Da Nang","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2170867,16.0582325],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"menuData":{"menuId":"1","selectedItems":["1"]}}] | [{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Duy Tan University","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2098773, 16.0600019],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":2,"menuData":{"menuId":"1","selectedItems":["1"]}}] |
    #     Then I should get the object result matches with
    #         | response      |
    #         | {"code":true} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"haidr","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                       |
    #         | {"res":{"list":[{"jobType":"shopForYou","delivery":true,"superHelper":false,"intercity":false,"request":{"paymentType":16}}]}} |

    # Scenario: 12. Check case save info payment type shop for you
    #     Given I want to register account
    #         | platform | fleetId | phone         | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | haidr   | +447400123789 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs shop for you "RESERVATION" with data
    #         | jupiter.jobType | request.paymentType | request.fleetId | request.vehicleTypeRequest | deliveryInfo.merchants                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | deliveryInfo.recipients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    #         | shopForYou      | 17                  | haidr           | Delivery                   | [{"name":"Nghia Huynh","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Hoang dieu, Da Nang","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2170867,16.0582325],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"menuData":{"menuId":"1","selectedItems":["1"]}}] | [{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Duy Tan University","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2098773, 16.0600019],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":2,"menuData":{"menuId":"1","selectedItems":["1"]}}] |
    #     Then I should get the object result matches with
    #         | response      |
    #         | {"code":true} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"haidr","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                       |
    #         | {"res":{"list":[{"jobType":"shopForYou","delivery":true,"superHelper":false,"intercity":false,"request":{"paymentType":17}}]}} |

    # Scenario: 13. Check case save info ETA fare
    #     Given I want to register account
    #         | platform | fleetId  | phone        | appType   | verifyCode | ime             | appName | rv      | password |
    #         | android  | delivery | +84348811100 | passenger | 2304       | 354741079903994 | MyCar   | 4.64200 | password |

    #     # cashBySender: 16, cashByRecipient: 17
    #     When Passenger create order jobs shop for you "RESERVATION" with data
    #         | jupiter.jobType | request.paymentType | request.fleetId | request.vehicleTypeRequest | deliveryInfo.merchants                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | deliveryInfo.recipients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    #         | shopForYou      | 17                  | delivery        | DeliveryFeePer             | [{"name":"Nghia Huynh","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Hoang dieu, Da Nang","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2170867,16.0582325],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"menuData":{"menuId":"1","selectedItems":["1"]}}] | [{"name":"QA Test","phone":"+447400123456","address":{"locationDetails":"","zoneId":"5d6f2c05e4b00ab898f0aa5a","zoneName":"Da Nang, Viet Nam","from":"gg","address":"Duy Tan University","addressDetails":{"cityName":"Da Nang","country":"Vietnam","floor":"","pointOfInterest":"","political":"Vietnam","postalCode":"550000","room":"","route":"","streetNumber":""},"instructionLink":"","geo":[108.2098773, 16.0600019],"zipCode":"550000","timezone":"Asia/Saigon","offset":"+07:00","businessName":"","cityName":"Da Nang","country":"VN"},"order":2,"menuData":{"menuId":"1","selectedItems":["1"]}}] |
    #     Then I should get the object result matches with
    #         | response      |
    #         | {"code":true} |
    #     And send a API "/api/booking/find" request with event and data
    #         | body                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
    #         | {"limit":50,"page":0,"sort":{"time":-1},"query":{"txtSearch":"","bookingService":"all","supportService":"all","corporateId":null,"bookingType":"all","rideType":"all","dateFrom":null,"dateTo":null,"operator":"","bookFrom":[],"carType":[],"status":["pending","pre","queue","offered","confirmed","booked","engaged","droppedOff","arrived","action"],"fleetId":"delivery","vip":null,"searchBy":"bookId","isDateRangeInputChanged":false,"zone":""}} |
    #     Then I should get the object result matches with
    #         | response                                                                                                                       |
    #         | {"res":{"list":[{"jobType":"shopForYou","delivery":true,"superHelper":false,"intercity":false,"request":{"paymentType":17}}]}} |

